# Generated by Django 5.1.4 on 2024-12-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('popis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mnozstvi', models.PositiveIntegerField()),
                ('min_zasoba', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistorieOperaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('typ_operace', models.CharField(choices=[('příjem', 'Příjem'), ('výdej', 'Výdej')], max_length=10)),
                ('mnozstvi', models.PositiveIntegerField()),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.historieoperaci')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.produkt')),
            ],
        ),
    ]
