# Generated by Django 5.1.4 on 2024-12-17 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_uzivatel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzivatel',
            new_name='ProfilUzivatele',
        ),
        migrations.RenameField(
            model_name='profiluzivatele',
            old_name='uzivatel',
            new_name='user',
        ),
    ]
