# Generated by Django 5.1.4 on 2025-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0008_historieoperaci_produkt_nazev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='produkty_obrazky/'),
        ),
    ]
